[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dystformer"
description = "Chronos Fine-Tuned on Dynamical Systems"
version = "0.1.0"
readme = "README.md"
license = { text = "MIT" }  # SPDX license identifier
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["numpy", "torch", "transformers", "accelerate", "dysts", "gluonts", "scipy", "scikit-learn", "tqdm", "wandb", "hydra-core"]

# Optional dependencies
[project.optional-dependencies]
tests = ["matplotlib", "statsmodels"]
numba = ["numba"]
chronos = ["datasets"] # huggingface datasets

# Package data
[tool.setuptools]
packages = ["dystformer", "dystformer.utils", "dystformer.chronos"] # dystformer.chronos.utils?