analysis:
  data_dir: /stor/work/AMDG_Gilpin_Summer2024/data
  split: final_base40/test_zeroshot
  save_dir: outputs
  plots_dir: figures
  compute_quantile_limits: false
  compute_max_lyapunov_exponents: false
  filter_ensemble: true
  filter_json_fname: failed_samples
  verbose: true
  attractor_tests:
    - check_boundedness
    # - check_not_transient
    # - check_stationarity
  
  check_not_transient:
    max_transient_prop: 0.2
    atol: 1e-3

  check_stationarity:
    p_value: 0.05

  check_boundedness:
    threshold: 1e4
    max_zscore: 5
    eps: 1e-10
