analysis:
  data_dir: /stor/work/AMDG_Gilpin_Summer2024/data/
  split: debug/train
  save_dir: outputs
  plots_dir: plots
  compute_quantile_limits: true
  compute_max_lyapunov_exponents: true
  filter_ensemble: true
  verbose: true
  attractor_tests:
    - check_not_transient

  check_not_transient:
    max_transient_prop: 0.2
    atol: 1e-3

  check_stationarity:
    p_value: 0.05
