defaults:
  - _self_
  - model
  - train
  - evaluation
  - dataset
  - dysts
  - analysis
  # - override hydra/job_logging: disabled 
  - override hydra/hydra_logging: disabled 

# string identifier for wandb runs and generic I/O
run_name: null

hydra:
  output_subdir: null
  run:
    dir: logs

  job_logging:
    handlers:
      file:
        mode: w
        # filename: ${hydra:run.dir}/${oc.select:run_name,${hydra:job.name}}.log

# wandb parameters
wandb:
  log: False
  project_name: dystformer
  entity: gilpinlab
  group_name: fine-tuning
  resume: False # allow
  resume_run_id: null
  tags: null