# directory containing files used for training data
train_data_dirs:
  - "/stor/work/AMDG_Gilpin_Summer2024/data/final_skew40/train/"
  - "/stor/work/AMDG_Gilpin_Summer2024/data/final_base40/train/"

# additional files to add to training data set
extra_train_data_paths: null
probability: null

use_quadratic_embedding: false

shuffle_buffer_length: 100_000

# minimum number of past points to use for training
min_past: 60

max_missing_prop: 0.9

fixed_dim: 3