sampling:
  data_dir: /stor/work/AMDG_Gilpin_Summer2024/data/
  sys_class: continuous_no_delay
  test_split: 0.3
  split_prefix: null
  rseed: 999
  reference_traj_length: 2048
  reference_traj_transient: 0.2
  reference_traj_n_periods: 5
  num_points: 4096
  num_periods: 10
  num_ics: 1
  num_param_perturbations: 4
  param_scale: 0.5
  split_coords: false
  standardize: false
  verbose: false
  multiprocessing: true
  debug_system: null
  silence_integration_errors: false
  save_params: true
  ignore_probability: 0.1
  sign_match_probability: 0.5

validator:
  enable: true
  verbose: false
  transient_time_frac: 0.05
  plot_save_dir: null
  save_failed_trajs: false

events:
  max_duration: 300
  instability_threshold: 1e8
  min_step: 1e-16
  verbose: true

skew:
  num_pairs: 5000

  # paths to train and test sets of non-skew systems for filtering
  # skew system samples into train/test sets
  train_nonskew_path: null
  test_nonskew_path: null
