eval:
  mode: predict
  data_path: /stor/work/AMDG_Gilpin_Summer2024/data/test/
  checkpoint_path: /stor/work/AMDG_Gilpin_Summer2024/checkpoints
  device: cuda:7
  torch_dtype: float32 # bfloat16?
  batch_size: 32
  num_systems: 10

  metrics_names:
    - mse
    - mae
    - smape
    - mape
    - r2_score
    - spearman
    - pearson

  forecast_save_dir: /stor/work/AMDG_Gilpin_Summer2024/data/eval/forecasts
  labels_save_dir: /stor/work/AMDG_Gilpin_Summer2024/data/eval/labels
  completions_save_dir: /stor/work/AMDG_Gilpin_Summer2024/data/eval/completions
  patch_input_save_dir: /stor/work/AMDG_Gilpin_Summer2024/data/eval/patch_input
  timestep_masks_save_dir: /stor/work/AMDG_Gilpin_Summer2024/data/eval/timestep_masks

  metrics_save_dir: /stor/work/AMDG_Gilpin_Summer2024/data/eval/metrics
  metrics_fname: metrics.json
  overwrite: false
  seed: 42

  # for generating forecasts and getting test split
  limit_prediction_length: true
  prediction_length: 64

  # window style can be either sampled or rolling
  # sampled: randomly samples windows from each timeseries (of length context_length) 
  # rolling: takes consecutive windows of context_length with a stride of
  #    window_stride from each timeseries
  # if window style == sampled, then num_test_instances is the # of windows to sample from each timeseries
  num_test_instances: 1
  window_style: sampled
  window_stride: 1
  split_coords: false
  verbose: true

# save_forecasts_to_npy: false
# agg_axis: null # 1 to keep dimensions separate
# num_samples: 20 # TODO: use this


chronos_eval:
  model_id: /stor/work/AMDG_Gilpin_Summer2024/checkpoints/checkpoint-80000
  temperature: null
  top_k: null
  top_p: null
  offset: -64
  num_rolls: 1