eval:
  mode: predict
  data_path: $WORK/data/test/
  checkpoint_path: /stor/work/AMDG_Gilpin_Summer2024/checkpoints
  output_dir: ./eval_results
  output_fname: null
  overwrite: false
  model_id: /stor/work/AMDG_Gilpin_Summer2024/checkpoints/checkpoint-80000
  device: cuda:7
  torch_dtype: bfloat16 # float32?
  batch_size: 32
  num_samples: 20
  temperature: null
  top_k: null
  top_p: null

  save_forecasts_to_npy: false
  forecast_save_dir: null

  agg_axis: null # 1 to keep dimensions separate

  # for generating forecasts and getting test split
  limit_prediction_length: true
  prediction_length: 64
  offset: -64
  num_rolls: 1

  # window style can be either sampled or rolling
  # sampled: randomly samples windows from each timeseries (of length context_length) 
  # rolling: takes consecutive windows of context_length with a stride of
  #    window_stride from each timeseries
  # if window style == sampled, then num_test_instances is the # of windows to sample from each timeseries
  num_test_instances: 1
  window_style: sampled
  window_stride: 1
  split_coords: false
  verbose: true
