eval:
  data_dir: /stor/work/AMDG_Gilpin_Summer2024/data
  split: train
  output_dir: ./eval_results
  output_fname: null
  overwrite: false
  model_id: /stor/work/AMDG_Gilpin_Summer2024/checkpoints/checkpoint-80000
  device: cuda:7
  torch_dtype: bfloat16 # float32?
  batch_size: 32
  num_samples: 20
  temperature: null
  top_k: null
  top_p: null

  agg_axis: null

  # for generating forecasts and getting test split
  prediction_length: 64
  offset: 64
  num_rolls: 1


  # this is only useful, as opposed to reading all systems from data_dir, if we want to havve
  # customizable prediction_length, offset, num_rolls, etc. for each system
  custom_dysts: null
  # - name: Lorenz96
  #   path: /stor/work/AMDG_Gilpin_Summer2024/data/train/Lorenz96
  #   prediction_length: 64
  #   offset: 64
  #   num_rolls: 1