base_style: ggplot

matplotlib_style:
  font:
    serif: Computer Modern Roman
    size: 10
  axes:
    titlesize: 12
    labelsize: 10
    linewidth: 0.75
    facecolor: white
    grid: false
  grid:
    color: gray
    linewidth: 0.5
    alpha: 0.5
  lines:
    linewidth: 1.5
    markersize: 5
  xtick:
    labelsize: 8
    major:
      size: 4
    minor:
      size: 2
    direction: in
  ytick:
    labelsize: 8
    major:
      size: 4
    minor:
      size: 2
    direction: in
  figure:
    figsize: [3.25, 2.5]
    dpi: 300
    autolayout: true
    facecolor: white
  legend:
    fontsize: 8
    title_fontsize: 9
    loc: upper right
    frameon: false
  savefig:
    dpi: 300
    format: pdf
    transparent: false
