# Backtest configs for the "in-domain" dynamical systems used for fine-tuning
# TODO: decide how we want to structure this

- name: Lorenz
  prediction_length: 32
  offset: 32
  num_rolls: 1
  data_filepath: "/stor/work/AMDG_Gilpin_Summer2024/data/train/Lorenz_dim-0.arrow"