# Backtest configs for the "in-domain" dynamical systems used for fine-tuning
data_dir: "/stor/work/AMDG_Gilpin_Summer2024/data/train/"
dysts:
- name: Lorenz
  prediction_length: 64
  offset: 64
  num_rolls: 1
- name: Lorenz96
  prediction_length: 64
  offset: 64
  num_rolls: 1
# - name: SprottD
#   prediction_length: 64
#   offset: 64
#   num_rolls: 1
# - name: Thomas
#   prediction_length: 64
#   offset: 64
#   num_rolls: 1